{
 "title": "NBP Weather Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Port Rel Wind Dir",
   "type": "briangann-gauge-panel",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 0 },
   "format": "degree",
   "targets": [
    {
     "query": "from(bucket: \"openrvdas\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"mwx1\")\r\n  |> filter(fn: (r) => r._field == \"MwxPortRelWindDir\")\r\n  "
    }
   ]
  },
  {
   "title": "Stbd Rel Wind Dir",
   "type": "briangann-gauge-panel",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 0 },
   "format": "degree",
   "targets": [
    {
     "query": "from(bucket: \"openrvdas\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"mwx1\")\r\n  |> filter(fn: (r) => r._field == \"MwxStbdRelWindDir\")\r\n  "
    }
   ]
  },
  {
   "title": "Relative wind speed",
   "type": "graph",
   "gridPos": { "h": 14, "w": 12, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "velocityknot" }
   ],
   "targets": [
    {
     "query": "from(bucket: \"openrvdas\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"mwx1\")\r\n  |> filter(fn: (r) => r._field == \"MwxPortRelWindSpeed\" or r._field == \"MwxStbdRelWindSpeed\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean)\r\n  |> yield(name: \"mean\")\r\n"
    }
   ]
  },
  {
   "title": "Port True Wind Dir",
   "type": "briangann-gauge-panel",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 7 },
   "format": "degree",
   "targets": [
    {
     "query": "from(bucket: \"openrvdas\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"true_wind\")\r\n  |> filter(fn: (r) => r._field == \"PortTrueWindDir\")\r\n  "
    }
   ]
  },
  {
   "title": "Stbd True Wind Dir",
   "type": "briangann-gauge-panel",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 7 },
   "format": "degree",
   "targets": [
    {
     "query": "from(bucket: \"openrvdas\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"true_wind\")\r\n  |> filter(fn: (r) => r._field == \"StbdTrueWindDir\")\r\n  "
    }
   ]
  }
 ]
}