apiVersion: 1

datasources:
  - name: OpenRVDAS Cache
    type: openrvdas-cache
    access: proxy
    isDefault: true
    orgId: 1
    version: 1
    editable: true
    url: 'ws://localhost/cds-ws'
    jsonData:
      path: '/resources'
      defaultTimeField: 
    secureJsonData: 
      apiKey: 'api-key'
