###################
config_templates:
  #################
  serial_net_config_template:
    readers:
    - class: SerialReader
      kwargs:
        baudrate: <<baud_rate|9600>>
        port: <<serial_port>>
    transforms:
    - class: TimestampTransform
    - class: PrefixTransform
      kwargs:
        prefix: <<logger>>
    writers:
    - class: UDPWriter
      kwargs:
        port: <<raw_udp_port>>
        destination: <<udp_destination>>

  serial_net_file_config_template:
    readers:
    - class: SerialReader
      kwargs:
        baudrate: <<baud_rate|9600>>
        port: <<serial_port>>
    transforms:
    - class: TimestampTransform
      mirror_to:
        class: LogfileWriter
        kwargs:
          filebase: <<file_root>>/<<logger>>/raw/<<cruise>>_<<logger>>
    - class: PrefixTransform
      kwargs:
        prefix: <<logger>>
    writers:
    - class: UDPWriter
      kwargs:
        port: <<raw_udp_port>>
        destination: <<udp_destination>>
