{
 "title": "LMG Weather Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Port Rel Wind Dir",
   "type": "briangann-gauge-panel",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 0 },
   "format": "degree",
   "targets": [
    {
     "query": "from(bucket: \"openrvdas\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"lmwx\")\r\n  |> filter(fn: (r) => r._field == \"MwxPortRelWindDir\")\r\n  |> last()\r\n  "
    }
   ]
  },
  {
   "title": "Stbd Rel Wind Dir",
   "type": "briangann-gauge-panel",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 0 },
   "format": "degree",
   "targets": [
    {
     "query": "from(bucket: \"openrvdas\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"lmwx\")\r\n  |> filter(fn: (r) => r._field == \"MwxStbdRelWindDir\")\r\n  |> last()\r\n  "
    }
   ]
  },
  {
   "title": "Relative wind speed",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "velocityknot" } },
   "targets": [
    {
     "query": "from(bucket: \"openrvdas\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"lmwx\")\r\n  |> filter(fn: (r) => r._field == \"MwxPortRelWindSpeed\" or r._field == \"MwxStbdRelWindSpeed\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean)\r\n  |> map(fn: (r) => ({ r with _value: r._value * 1.944 }))\r\n  |> yield(name: \"mean\")\r\n"
    }
   ]
  },
  {
   "title": "Port True Wind Dir",
   "type": "briangann-gauge-panel",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 7 },
   "format": "degree",
   "targets": [
    {
     "query": "from(bucket: \"openrvdas\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"true_wind\")\r\n  |> filter(fn: (r) => r._field == \"PortTrueWindDir\")\r\n  |> last()\r\n  "
    }
   ]
  },
  {
   "title": "Stbd True Wind Dir",
   "type": "briangann-gauge-panel",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 7 },
   "format": "degree",
   "targets": [
    {
     "query": "from(bucket: \"openrvdas\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"true_wind\")\r\n  |> filter(fn: (r) => r._field == \"StbdTrueWindDir\")\r\n  |> last()\r\n  "
    }
   ]
  },
  {
   "title": "True wind speed",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "velocityknot" } },
   "targets": [
    {
     "query": "from(bucket: \"openrvdas\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"true_wind\")\r\n  |> filter(fn: (r) => r._field == \"PortTrueWindSpeed\" or r._field == \"StbdTrueWindSpeed\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean)\r\n  |> map(fn: (r) => ({ r with _value: r._value * 1.944 }))\r\n  |> yield(name: \"mean\")\r\n"
    }
   ]
  },
  {
   "title": "Baro Pressure",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "pressurembar" } },
   "targets": [
    {
     "query": "from(bucket: \"openrvdas\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"lmwx\")\r\n  |> filter(fn: (r) => r._field == \"MwxBarometer\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean)\r\n  |> yield(name: \"mean\")\r\n"
    }
   ]
  },
  {
   "title": "Air Temperature",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "query": "from(bucket: \"openrvdas\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"lmwx\")\r\n  |> filter(fn: (r) => r._field == \"MwxAirTemp\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean)\r\n  |> yield(name: \"mean\")\r\n"
    }
   ]
  },
  {
   "title": "Relative Humidity",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "humidity" } },
   "targets": [
    {
     "query": "from(bucket: \"openrvdas\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"lmwx\")\r\n  |> filter(fn: (r) => r._field == \"MwxAirRelHumid\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean)\r\n  |> yield(name: \"mean\")\r\n"
    }
   ]
  },
  {
   "title": "Radiation",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "mvolt" } },
   "targets": [
    {
     "query": "from(bucket: \"openrvdas\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"lmwx\")\r\n  |> filter(fn: (r) => r._field == \"MwxPAR\" or \r\n            r._field == \"MwxPIRThermo\" or r._field == \"MwxPSP\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean)\r\n  |> yield(name: \"mean\")\r\n"
    }
   ]
  }
 ]
}