{
 "title": "LMG All-in-One",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "GPS Date and Time",
   "type": "stat",
   "gridPos": { "h": 3, "w": 15, "x": 1, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"openrvdas\")\r\n  |> range(start:-10m)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"lsep\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"S330GPSDate\")\r\n  |> last()"
    }
   ]
  },
  {
   "title": "Latitude",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "degree" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "query": "from(bucket: \"openrvdas\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"lsep\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"S330Latitude\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "  ",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 5, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"openrvdas\")\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) =>\r\n    r._measurement == \"lsep\" and r._field == \"S330NorS\"\r\n  )\r\n  |> last()\r\n  |> toString()"
    }
   ]
  },
  {
   "title": "Longitude",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 7, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "degree" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "query": "from(bucket: \"openrvdas\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"lsep\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"S330Longitude\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "   ",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 12, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"openrvdas\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"lsep\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"S330EorW\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "Depth",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 14, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "lengthm" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "query": "from(bucket: \"openrvdas\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"lknu\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"KnudDepthLF\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Gyro Heading, True",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "degree" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"openrvdas\")\r\n  |> range(start: -5m)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"lsep\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"S330HeadingTrue\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Port True Wind Dir",
   "type": "briangann-gauge-panel",
   "gridPos": { "h": 6, "w": 4, "x": 5, "y": 6 },
   "format": "degree",
   "targets": [
    {
     "query": "from(bucket: \"openrvdas\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"true_wind\")\r\n  |> filter(fn: (r) => r._field == \"PortTrueWindDir\")\r\n  |> last()\r\n  "
    }
   ]
  },
  {
   "title": "Stbd True Wind Dir",
   "type": "briangann-gauge-panel",
   "gridPos": { "h": 6, "w": 4, "x": 9, "y": 6 },
   "format": "degree",
   "targets": [
    {
     "query": "from(bucket: \"openrvdas\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"true_wind\")\r\n  |> filter(fn: (r) => r._field == \"StbdTrueWindDir\")\r\n  |> last()\r\n  "
    }
   ]
  },
  {
   "title": "SSTemp",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 13, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"openrvdas\")\r\n  |> range(start: -5m)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"lrtm\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"RTMPTemp\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Course Made Good",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "degree" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"openrvdas\")\r\n  |> range(start: -5m)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"lsep\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"S330CourseTrue\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Salinity",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 13, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"openrvdas\")\r\n  |> range(start: -5m)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"utsg\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"TSG2Salinity\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Speed Over Ground",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "velocityknot" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"openrvdas\")\r\n  |> range(start: -1m)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"lsep\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"S330SpeedKt\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Port Wind Speed",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 5, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "velocityknot" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"openrvdas\")\r\n  |> range(start: -1m)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"true_wind\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"PortTrueWindSpeed\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> map(fn: (r) => ({ r with _value: r._value * 1.944 }))\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Stbd Wind Speed",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 9, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "velocityknot" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"openrvdas\")\r\n  |> range(start: -1m)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"true_wind\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"StbdTrueWindSpeed\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> map(fn: (r) => ({ r with _value: r._value * 1.944 }))\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Flow 1",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 13, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"openrvdas\")\r\n  |> range(start: -5m)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"lsea\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"SeaFlow1\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "PAR",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "mvolt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"openrvdas\")\r\n  |> range(start: -1m)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"lmwx\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"MwxPAR\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Air Temp",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 5, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"openrvdas\")\r\n  |> range(start: -1m)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"lmwx\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"MwxAirTemp\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "PCO2",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 9, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"openrvdas\")\r\n  |> range(start: -5m)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"lpco\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"PCO2VCO2Concentration\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Flow 3",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 13, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"openrvdas\")\r\n  |> range(start: -5m)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"lsea\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"SeaFlow3\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "PIR",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "mvolt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"openrvdas\")\r\n  |> range(start: -1m)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"lmwx\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"MwxPIRThermo\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Humidity",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 5, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"openrvdas\")\r\n  |> range(start: -1m)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"lmwx\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"MwxAirRelHumid\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Oxygen",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 9, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"openrvdas\")\r\n  |> range(start: -1m)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"loxy\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"OxyOxygen\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "XMiss",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 13, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"openrvdas\")\r\n  |> range(start: -5m)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"lsea\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"SeaTransmissometer\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> map(fn: (r) => ({ r with _value: (r._value - 0.060)/(4.718 - 0.060) }))\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "PSP",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "mvolt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"openrvdas\")\r\n  |> range(start: -1m)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"lmwx\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"MwxPSP\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Barometer",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 5, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "pressurembar" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"openrvdas\")\r\n  |> range(start: -1m)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"lmwx\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"MwxBarometer\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Oxy Sat",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 9, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"openrvdas\")\r\n  |> range(start: -1m)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"loxy\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"OxySaturation\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Fluoro",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 13, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "conmgm3" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"openrvdas\")\r\n  |> range(start: -5m)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"ldfl\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"FluorChlorSignal\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  }
 ]
}